# I.11.19: F = x_1*y_1 + x_2*y_2 + x_3*y_3: without noise

In [56]:
from codes.bsr_class_I_11_19 import symreg
from codes.bsr_class_I_11_19 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [47]:
I_11_19_data = pd.read_csv("I_11_19_data.csv")

# x1: x1; x2: x2; x3: x3; x4: y1; x5: y2; x6: y3. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_11_19_data.loc[1:1000, ['x1', 'x2', 'x3', 'y1', 'y2', 'y3']]
X = X.reset_index(drop=True)
# y = x1*x4 + x2*x5 + x3*x6
y = I_11_19_data.loc[1:1000, ['I.11.19_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True)

In [53]:
K = 10
MM = 100 # number of iterations
hyper_params = [{'treeNum': 10, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [54]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)

time.time() - st

1708.2369000911713

In [57]:
## saving the results
BSRresults_I_11_19_K10 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_11_19_K10.pkl", "wb") as f:
    pickle.dump(BSRresults_I_11_19_K10, f)

In [59]:
rmse

[2408.9833925827525,
 2432.2903986963215,
 2432.3708963421395,
 2374.2429631493746,
 2428.341079783197,
 2432.3816168117655,
 2399.019440375749,
 2077.3733236037,
 2430.604571540569,
 2432.171980221919]

In [60]:
model_expression

[['x[0]+x[5]',
  'x[0]+x[3]+((x[5])*(x[0]))*((x[5])*(x[3]))',
  '(x[2]+x[1])*(x[2])',
  '((x[5])*(x[5])+x[2]+x[3])*((x[3]+(x[2])*(x[1])+x[3])*(x[0]))',
  'x[3]+x[3]+x[2]',
  'x[1]+(x[1])*(x[0])',
  'x[3]+x[3]+(x[4])*((x[5])*(x[1]))',
  '(x[2])*(x[4])',
  '((x[2])*(x[1]))*(x[5])',
  'x[3]+x[3]'],
 ['x[2]+x[1]+x[1]+x[1]',
  '((x[4])*(x[1]))*(x[5]+x[5]+x[2])',
  'x[5]+x[5]+x[2]+(x[3]+x[1])*(x[2])',
  '((x[5])*(x[0]))*(x[5])+x[2]',
  '(x[5])*(x[2])+x[1]',
  '(x[1])*((x[4])*(x[0]))+x[5]',
  'x[3]+x[3]+(x[1])*(x[4]+x[4])',
  '(x[0])*(x[4]+x[5]+x[3])+x[2]',
  '((x[2]+x[0])*(x[3]))*(x[2]+x[4])+(x[4])*((x[2])*(x[5]))',
  'x[2]+x[2]'],
 ['(x[2]+x[4]+x[4])*(x[3]+(x[2])*(x[1])+x[0])',
  'x[4]+x[5]+x[5]+x[2]+x[0]',
  '((x[4])*(x[1])+x[2])*(x[0])',
  'x[0]+(x[5])*((x[1])*(x[1])+x[0])+x[0]',
  '(x[0])*((x[0])*(x[3]))',
  '(x[0])*((x[5])*(x[2])+x[4]+(x[0])*(x[3]))+x[4]+((x[1])*(x[2]))*((x[1])*(x[3]))',
  '((x[3])*(x[0]))*(x[5]+x[3]+x[4]+x[5]+x[4])',
  '(x[0])*(x[3])+x[5]+x[4]+(x[5])*(x[2])',
  '(x[1])

# I.11.19: F = x_1*y_1 + x_2*y_2 + x_3*y_3: with noise, sigma_sq = 1

In [29]:
from codes.bsr_class_I_11_19 import symreg
from codes.bsr_class_I_11_19 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [30]:
I_11_19_data = pd.read_csv("I_11_19_data.csv")

np.random.seed(10)

## noise: sigma_sq = 1
sigma = 1

# x1: x1; x2: x2; x3: x3; x4: y1; x5: y2; x6: y3. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_11_19_data.loc[1:1000, ['x1', 'x2', 'x3', 'y1', 'y2', 'y3']]
X = X.reset_index(drop=True)
# y = x1*x4 + x2*x5 + x3*x6
y = I_11_19_data.loc[1:1000, ['I.11.19_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True) + pd.Series(np.random.normal(0, sigma, X.shape[0])) # noisy vector

In [31]:
K = 10
MM = 100 # number of iterations
hyper_params = [{'treeNum': 10, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [32]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)

time.time() - st

ValueError: Data must be 1-dimensional, got ndarray of shape (1000, 1000) instead

In [91]:
## saving the results
BSRresults_I_11_19_K10_sigma_sq_1 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st, 'sigma_sq': sigma}
with open("BSRresults_I_11_19_K10_sigma_sq_1.pkl", "wb") as f:
    pickle.dump(BSRresults_I_11_19_K10, f)

In [89]:
rmse

[2430.788535887575,
 2428.648928653748,
 2430.369879645858,
 2416.559310815,
 2421.3837058639106,
 2372.250053368044,
 2430.7524819834507,
 2175.8530402409638,
 2407.648093568365,
 2430.725740987222]

In [90]:
model_expression

[['(x[4])*(x[1])',
  '(x[2])*(x[3]+x[5])',
  '(x[0])*(x[5])+x[0]+x[4]',
  '(x[1])*(x[3])',
  '(x[2])*((x[2])*(x[0]+x[2]))',
  '(x[3])*(x[5]+x[2]+x[3]+x[0])',
  '(x[5]+(x[3])*(x[5])+x[4])*(x[4])',
  '((x[0])*(x[3]+x[2]))*(x[0]+x[5])',
  'x[5]+(x[2])*(x[5])',
  'x[2]+x[3]'],
 ['(x[4])*(((x[2])*(x[1]+x[4]+x[5]+x[4]))*(x[3]))',
  '(x[5])*(x[2])+x[0]',
  '(x[5])*((x[1])*(x[4]+x[0]))',
  '((x[1])*(x[3]))*((x[3])*(x[0])+(x[0])*(x[0])+x[4])',
  '(x[0])*((x[4])*(x[5]+x[2]))+x[4]+x[1]',
  'x[3]+(x[0]+x[0])*(x[4])',
  '(x[5])*((x[2])*(x[5])+x[2])',
  '(x[1])*(x[1]+(x[1])*(x[4])+x[0])',
  '(x[4])*(x[5]+x[5])+x[4]',
  '(x[0])*(x[2]+x[2]+x[5])'],
 ['(x[5])*(x[2]+x[2]+x[2])',
  '(x[3])*(x[1])',
  'x[3]+x[0]',
  '(((x[5])*(x[4]))*(x[0]))*(x[2])',
  '(x[0])*(x[2]+x[3]+x[3])+((x[0])*(x[1]))*(x[3])+(x[1])*(x[1])',
  '(x[3])*(x[4])+x[1]',
  '((x[2])*(x[3]))*(x[2]+(x[4])*(x[0]))',
  'x[5]+x[2]+x[0]+x[0]+(x[2])*(x[3])+x[4]+(x[2])*((x[1])*(x[1]))',
  'x[4]+x[3]+x[0]+x[0]',
  '(x[0])*(x[5])'],
 ['(x[4]+x[3])*

# I.12.2: F = q1q2/4*epsilon*(r**2): without noise

In [39]:
from codes.bsr_class_I_12_2 import symreg
from codes.bsr_class_I_12_2 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [61]:
I_12_2_data = pd.read_csv("I_12_2_data.csv")

# x1: q1**2 / epsilon*(r**2); x2: q2/q1. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_12_2_data.loc[0:999, ['x1', 'x2']]
X = X.reset_index(drop=True)
# y:4piF = x1*x2
y = I_12_2_data.loc[0:999, ['I.12.2_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True)

In [62]:
K = 2
MM = 100 # number of iterations
hyper_params = [{'treeNum': 2, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [63]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

time.time() - st

0
1
2
3
4
5
6
7
8
9


253.02364802360535

In [101]:
## saving the results
BSRresults_I_12_2_K2 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_12_2_K2.pkl", "wb") as f:
    pickle.dump(BSRresults_I_12_2_K2, f)

In [64]:
min(rmse), rmse.index(min(rmse))

(3.881480762181475e-08, 7)

In [69]:
model_expression[2]

['(x[0]+(x[1])*(x[0]))*(x[0])', '((x[1])*(x[1]))*((x[1])*(x[1]))']

In [65]:
rmse

[9.69754210414491e-07,
 8.718762824737028e-07,
 0.008447889873516735,
 1.4280687679720506e-06,
 0.013057520186726655,
 0.021969171069083946,
 4.844790947928192e-08,
 3.881480762181475e-08,
 0.0009548390669158683,
 0.004519470287154278]

In [68]:
beta_hat[2]

array([[ 0.01029741],
       [ 0.06466928],
       [-5.86262582]])

# I.12.2: F = q1q2/4*epsilon*(r**2): with noise, sigma_sq = 4 

In [70]:
from codes.bsr_class_I_12_2 import symreg
from codes.bsr_class_I_12_2 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [71]:
I_12_2_data = pd.read_csv("I_12_2_data.csv")

np.random.seed(10)

## noise: sigma_sq = 4
sigma = 4 ** 0.5

# x1: q1**2 / epsilon*(r**2); x2: q2/q1. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_12_2_data.loc[0:999, ['x1', 'x2']]
X = X.reset_index(drop=True)
# y:4piF = x1*x2
y = I_12_2_data.loc[0:999, ['I.12.2_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True) + pd.Series(np.random.normal(0, sigma, X.shape[0])) # noisy vector

In [72]:
K = 2
MM = 100 # number of iterations
hyper_params = [{'treeNum': 2, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [73]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

time.time() - st

0
1
2
3
4
5
6
7
8
9


201.05101013183594

In [ ]:
## saving the results
BSRresults_I_12_2_K2_sigma_sq_4 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_12_2_K2_sigma_sq_4.pkl", "wb") as f:
    pickle.dump(BSRresults_I_12_2_K2_sigma_sq_4, f)

In [74]:
min(rmse), rmse.index(min(rmse))

(1.8668801055455013, 5)

In [75]:
model_expression[5]

['x[1]+x[0]', '(x[0])*((x[1])*(x[0]))']

In [77]:
beta_hat[5]

array([[ 0.28165377],
       [-0.28478157],
       [ 0.63215877]])

In [76]:
rmse

[1.8830246090530405,
 1.8674772032590674,
 1.8676871891617328,
 1.8671194308277832,
 1.8674772347249928,
 1.8668801055455013,
 1.867477367221286,
 1.87064230947654,
 1.8674772035656833,
 1.8674772032590394]

# I.13.12: U = G*m1*m2*(1/r2 - 1/r1): without noise

In [103]:
from codes.bsr_class_I_13_12 import symreg
from codes.bsr_class_I_13_12 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [104]:
I_13_12_data = pd.read_csv("I_13_12_data.csv")
# x1: G*(m1**2) / r1; x2: m2/m1; x3: r2/r1. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_13_12_data.loc[1:1000, ['x1', 'x2', 'x3']]
X = X.reset_index(drop=True)
# y:U = x1*x2 - (x1*x2)/x3
y = I_13_12_data.loc[1:1000, ['I.13.12_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True)

In [105]:
K = 5
MM = 100 # number of iterations
hyper_params = [{'treeNum': 5, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [106]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

time.time() - st

0
1
2
3
4
5
6
7
8
9


1238.5186820030212

In [12]:
## saving the results
BSRresults_I_13_12_K5 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_13_12_K5.pkl", "wb") as f:
    pickle.dump(BSRresults_I_13_12_K5, f)

In [109]:
min(rmse), rmse.index(min(rmse))

(0.016745103497940672, 0)

In [111]:
rmse

[0.016745103497940672,
 45.382797578597874,
 0.04935970471295213,
 0.05175872113731233,
 0.04576415000684497,
 0.1642100137622485,
 0.11891276546293833,
 0.04220127602322634,
 31.17917586446777,
 0.058641269620801684]

In [113]:
model_expression[0]

['(((x[0])*(x[1]))*(x[0]))*(x[2])',
 '1/[1/[(x[2])*(x[2])]]',
 '(1/[x[2]+x[2]])*(x[0])',
 '(x[1])*(x[2])',
 'x[0]+x[1]']

In [11]:
beta_hat

[array([[ 0.05302967],
        [ 0.55256503],
        [ 0.05296339],
        [-0.01822351],
        [ 0.84040376],
        [-0.99999196]]),
 array([[ 5.61602173],
        [-4.56509461],
        [-0.05006882],
        [-0.88863   ],
        [-0.6185267 ],
        [ 0.36154323]]),
 array([[-0.02175444],
        [-0.99998881],
        [-0.06071812],
        [ 0.01410277],
        [ 0.43233544],
        [-0.07516263]]),
 array([[ 1.76973378e-01],
        [-8.05733258e-04],
        [ 8.97435764e-01],
        [ 9.91190086e-01],
        [-9.99989306e-01],
        [-4.70893078e-01]]),
 array([[-0.06860992],
        [ 1.23283963],
        [-0.29610861],
        [ 0.34465849],
        [ 0.69684954],
        [-0.50213862]]),
 array([[ 0.24355836],
        [ 0.84481946],
        [ 0.29176284],
        [ 0.2126206 ],
        [ 0.02273691],
        [-1.00000784]]),
 array([[-7.72468877e-03],
        [ 1.61786277e-01],
        [-5.00032210e-01],
        [ 3.81420871e-01],
        [ 5.84606482e-05],
 

# I.13.12: U = G*m1*m2*(1/r2 - 1/r1): with noise sigma_sq = 1.5

In [114]:
from codes.bsr_class_I_13_12 import symreg
from codes.bsr_class_I_13_12 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [122]:
I_13_12_data = pd.read_csv("I_13_12_data.csv")

np.random.seed(10)

## noise: sigma_sq = 1.5
sigma = 1.50 ** 0.5

# x1: G*(m1**2) / r1; x2: m2/m1; x3: r2/r1. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_13_12_data.loc[0:999, ['x1', 'x2', 'x3']]
X = X.reset_index(drop=True)
# y:U = x1*x2 - (x1*x2)/x3
y = I_13_12_data.loc[0:999, ['I.13.12_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True) + pd.Series(np.random.normal(0, sigma, X.shape[0])) # noisy vector

In [123]:
K = 5
MM = 100 # number of iterations
hyper_params = [{'treeNum': 5, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [124]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

time.time() - st

0
1
2
3
4
5
6
7
8
9


914.7910370826721

In [30]:
## saving the results
BSRresults_I_13_12_K5_sigma_sq_1_5 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_13_12_K5_sigma_sq_1.5.pkl", "wb") as f:
    pickle.dump(BSRresults_I_13_12_K5_sigma_sq_1_5, f)

In [125]:
min(rmse), rmse.index(min(rmse))

(1.2135604416958017, 2)

In [126]:
rmse[3]

[1.6985888746851774,
 2.258110154506329,
 1.2135604416958017,
 30.998597565658546,
 31.3129278814682,
 31.266814581428232,
 1.6556830426936253,
 1.9211646192864191,
 31.220866392477337,
 1.260281081196234]

In [127]:
model_expression[3]

['x[0]+x[2]+1/[x[0]]',
 '1/[x[1]]',
 '1/[x[2]+x[2]]',
 '(x[2])*(x[0])+x[0]',
 'x[2]+x[1]']

In [128]:
beta_hat[3]

array([[ 6.85860713],
       [-6.85778231],
       [ 4.34163535],
       [-1.77648749],
       [ 0.78415411],
       [ 3.93070755]])

# I.18.4: r = (m1*r1 + m2*r2)/m2: without noise

In [37]:
from codes.bsr_class_I_18_4 import symreg
from codes.bsr_class_I_18_4 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [38]:
I_18_4_data = pd.read_csv("I_18_4_data.csv")
# x1: r1; x2: m2/m1; x3: r2/r1. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_18_4_data.loc[1:1000, ['x1', 'x2', 'x3']]
X = X.reset_index(drop=True)
# y:r = x1/x2 + (x1*x3)
y = I_18_4_data.loc[1:1000, ['I.18.4_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True)

In [39]:
K = 3
MM = 100 # number of iterations
hyper_params = [{'treeNum': 3, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [40]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)

time.time() - st

1055.9662382602692

In [44]:
## saving the results
BSRresults_I_18_4_K3 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_18_4_K3.pkl", "wb") as f:
    pickle.dump(BSRresults_I_18_4_K3, f)

In [41]:
rmse

[90.02221976309467,
 87.90962231457836,
 90.50153463791713,
 90.52489043336816,
 90.52488600306185,
 90.22409937700917,
 90.52477481336696,
 90.5248965955731,
 90.52489659557713,
 90.52489659557479]

In [42]:
model_expression

[['1/[(x[1])*(x[2])]', '1/[x[1]]', '1/[1/[x[0]]]'],
 ['(x[1])*((x[0])*(1/[x[1]]))',
  '(((x[2])*((x[0])*(((x[2])*(x[1]))*(x[0]))))*(x[1]))*(x[0])',
  '1/[x[1]]'],
 ['(1/[x[1]])*((x[2])*(1/[1/[x[0]]]))',
  '(1/[x[2]])*((x[0])*(1/[x[1]]))',
  '(x[1])*(x[0])'],
 ['1/[1/[(x[1])*(x[1])]]', '(x[2])*(x[0])', '1/[(x[1])*(1/[x[0]])]'],
 ['(x[0])*(1/[x[1]])',
  '1/[1/[(x[0])*(x[2])]]',
  '(((x[2])*(x[0]))*(x[0]))*(1/[x[1]])'],
 ['1/[(1/[x[0]])*(x[2])]', '1/[(x[1])*(x[1])]', '(x[2])*((x[0])*(x[2]))'],
 ['1/[(1/[x[1]])*(1/[(x[1])*(x[2])])]', '(1/[x[1]])*(x[0])', '(x[2])*(x[0])'],
 ['1/[1/[1/[x[2]]]]',
  '(1/[x[1]])*(x[0])',
  '1/[(x[1])*(1/[((x[1])*(x[2]))*(x[0])])]'],
 ['(x[2])*(x[0])',
  '1/[1/[1/[((x[0])*(x[2]))*(x[2])]]]',
  '((1/[x[1]])*(x[1]))*(1/[(1/[x[0]])*(x[1])])'],
 ['(x[0])*(1/[x[1]])',
  '1/[1/[x[1]]]',
  '1/[(x[1])*(1/[((x[1])*(x[0]))*(x[2])])]']]

In [43]:
beta_hat

[array([[ 0.34523879],
        [ 1.56509526],
        [-1.96696139],
        [ 2.14288977]]),
 array([[-7.01007986e-01],
        [ 2.14512341e+00],
        [ 1.37821246e-03],
        [ 7.21914155e-01]]),
 array([[-0.07576807],
        [ 1.26291354],
        [ 0.23844584],
        [ 0.54913945]]),
 array([[6.30955834e-07],
        [3.03942082e-08],
        [9.99999645e-01],
        [9.99999862e-01]]),
 array([[3.51535213e-06],
        [9.99997857e-01],
        [9.99997647e-01],
        [1.24390360e-06]]),
 array([[-0.00223998],
        [ 1.56048624],
        [ 0.11011843],
        [ 0.37011446]]),
 array([[7.96859997e-06],
        [2.85201490e-07],
        [9.99998426e-01],
        [9.99995223e-01]]),
 array([[-4.38465598e-08],
        [ 3.26379840e-07],
        [ 9.99999879e-01],
        [ 9.99999922e-01]]),
 array([[ 5.99844523e-07],
        [ 9.99999781e-01],
        [-1.72508009e-07],
        [ 9.99999944e-01]]),
 array([[2.27998849e-07],
        [9.99999946e-01],
        [3.4625672

# I.18.4: r = (m1*r1 + m2*r2)/m2: with noise, sigma_sq = 2.5

In [45]:
from codes.bsr_class_I_18_4 import symreg
from codes.bsr_class_I_18_4 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [46]:
I_18_4_data = pd.read_csv("I_18_4_data.csv")

np.random.seed(10)

## noise: sigma_sq = 2.5
sigma = 2.5 ** 0.5

# x1: r1; x2: m2/m1; x3: r2/r1. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_18_4_data.loc[1:1000, ['x1', 'x2', 'x3']]
X = X.reset_index(drop=True)
# y:r = x1/x2 + (x1*x3)
y = I_18_4_data.loc[1:1000, ['I.18.4_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True) + pd.Series(np.random.normal(0, sigma, X.shape[0])) # noisy vector

In [47]:
K = 3
MM = 100 # number of iterations
hyper_params = [{'treeNum': 3, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [48]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)

time.time() - st

430.9647810459137

In [52]:
## saving the results
BSRresults_I_18_4_K3_sigma_sq_2_5 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_18_4_K3_sigma_sq_2.5.pkl", "wb") as f:
    pickle.dump(BSRresults_I_18_4_K3_sigma_sq_2_5, f)

In [49]:
rmse

[95.94906863526408,
 89.75334459704185,
 91.72782073934155,
 97.98182105268523,
 98.00275502479083,
 98.78842006521175,
 86.34964827389321,
 98.35891426844792,
 91.86042830383806,
 93.30633074927074]

In [50]:
model_expression

[['1/[x[0]]',
  '(1/[((x[2])*(x[1]))*(1/[x[0]])])*(x[2])',
  '(1/[x[1]])*((x[0])*(1/[x[1]]))'],
 ['1/[(1/[x[1]])*(x[0])]',
  '1/[(x[0])*((1/[x[0]])*(1/[1/[x[2]]]))]',
  '((1/[x[2]])*(1/[x[0]]))*(1/[x[2]])'],
 ['(x[2])*(((x[1])*((x[2])*(x[0])))*(x[2]))',
  '((x[1])*(x[0]))*(x[2])',
  '1/[(x[1])*(x[2])]'],
 ['(x[0])*(1/[x[2]])', '(x[2])*(x[1])', '1/[x[0]]'],
 ['1/[1/[x[0]]]', '1/[x[1]]', '(1/[x[1]])*((1/[x[0]])*(x[1]))'],
 ['1/[(((x[0])*(x[2]))*(x[1]))*(x[0])]',
  '1/[1/[(x[0])*(x[1])]]',
  '(1/[x[2]])*(x[0])'],
 ['1/[x[2]]', '(x[1])*(1/[x[1]])', '(x[2])*(x[2])'],
 ['((x[1])*(((x[0])*(x[0]))*(x[0])))*((1/[x[0]])*(1/[x[2]]))',
  '1/[(x[1])*(x[1])]',
  '1/[1/[x[0]]]'],
 ['(x[2])*(x[2])', '(1/[x[0]])*(x[1])', '(x[1])*(x[0])'],
 ['1/[(x[0])*(1/[1/[x[1]]])]', '1/[x[1]]', '(x[1])*((x[1])*(x[0]))']]

In [51]:
beta_hat

[array([[ 2.19365803],
        [-0.7700369 ],
        [ 1.23393452],
        [-0.12018092]]),
 array([[ 1.07537124],
        [-0.16709739],
        [ 3.70770075],
        [-1.40178135]]),
 array([[ 0.0358638 ],
        [-0.06287469],
        [ 0.84864391],
        [ 1.03636026]]),
 array([[ 0.46073894],
        [ 1.70944502],
        [ 0.35130666],
        [-0.30261181]]),
 array([[-0.58378947],
        [ 2.19345956],
        [ 0.64375872],
        [-0.06093003]]),
 array([[-0.00951876],
        [ 0.01602981],
        [ 0.58177418],
        [ 1.53925105]]),
 array([[-2.61708646],
        [ 6.09921015],
        [-2.61708646],
        [ 1.40788084]]),
 array([[-0.45541743],
        [-0.06045373],
        [ 0.18310239],
        [ 2.46072038]]),
 array([[ 2.56985737],
        [-1.0781203 ],
        [-0.2537086 ],
        [ 1.44336796]]),
 array([[ 0.69328783],
        [-0.97140252],
        [ 2.42646428],
        [ 0.25143497]])]

# I.12.11: F = q*(Ef+Bv*sin(theta)), without noise

In [78]:
from codes.bsr_class_I_12_11 import symreg
from codes.bsr_class_I_12_11 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [79]:
I_12_11_data = pd.read_csv("I_12_11_data.csv")

# x1: Ef*q; x2: Bv/Ef; x3: theta. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_12_11_data.loc[1:1000, ['x1', 'x2', 'x3']]
X = X.reset_index(drop=True)
# y:F = x1 + (x1*x2*sin(x3))
y = I_12_11_data.loc[1:1000, ['I.12.11_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True)

In [80]:
K = 3
MM = 100 # number of iterations
hyper_params = [{'treeNum': 3, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [81]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

time.time() - st

0
1
2
3
4
5
6
7
8
9


157.1590769290924

In [60]:
## saving the results
BSRresults_I_12_11_K3 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_12_11_K3.pkl", "wb") as f:
    pickle.dump(BSRresults_I_12_11_K3, f)

In [83]:
min(rmse), rmse.index(min(rmse))

(6.363989255262762, 0)

In [84]:
model_expression[0]

['((x[1])*(sin(x[2])))*((x[1])*(x[2]))', 'sin(x[2])', 'sin((x[0])*(x[2]))']

In [85]:
beta_hat[0]

array([[ 3.09582238],
       [-0.16317558],
       [ 9.31833738],
       [-1.84391733]])

# I.12.11: F = q*(Ef+Bv*sin(theta)), with noise sigma_sq = 2

In [86]:
from codes.bsr_class_I_12_11 import symreg
from codes.bsr_class_I_12_11 import BSR
import pandas as pd
import numpy as np
import random
import time
import pickle

In [94]:
I_12_11_data = pd.read_csv("I_12_11_data.csv")

np.random.seed(10)

## noise: sigma_sq = 2
sigma = 2 ** 0.5

# x1: Ef*q; x2: Bv/Ef; x3: theta. Note that feature index starts from 0.
## sub-sampling 1000 data points out of 10000
X = I_12_11_data.loc[0:999, ['x1', 'x2', 'x3']]
X = X.reset_index(drop=True)
# y:F = x1 + (x1*x2*sin(x3))
y = I_12_11_data.loc[0:999, ['I.12.11_data$Y']]
y = y.squeeze(axis=0)
y = y.iloc[:,0]
y = y.rename("x")
y = y.reset_index(drop=True) + pd.Series(np.random.normal(0, sigma, X.shape[0])) # noisy vector

In [95]:
K = 3
MM = 100 # number of iterations
hyper_params = [{'treeNum': 3, 'itrNum': 100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [96]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X, y)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

time.time() - st

0
1
2
3
4
5
6
7
8
9


152.2785038948059

In [70]:
## saving the results
BSRresults_I_12_11_K3_sigma_sq_2 = {'X': X, 'y': y, 'rmse': rmse, 'expr': model_expression, 'runtime': time.time() - st}
with open("BSRresults_I_12_11_K3_sigma_sq_2.pkl", "wb") as f:
    pickle.dump(BSRresults_I_12_11_K3_sigma_sq_2, f)

In [98]:
min(rmse), rmse.index(min(rmse))

(3.2643906125340423, 9)

In [100]:
model_expression[1]

['sin((x[0])*(x[2]))', 'sin((x[2])*(x[0]))', '(x[2])*(x[1])']

In [101]:
beta_hat[1]

array([[ 3.0543957 ],
       [-0.08397284],
       [-0.08397284],
       [ 0.10745843]])

In [102]:
rmse[1]

10.31105870050605