In [1]:
import pandas as pd
import numpy as np
import random
import time
# from codes.bsr_class import symreg
from codes.bsr_class_Copy1 import BSR

In [2]:
def f1(n_train=100,n_test=30):
    """
    y = 1.35 * (x0*x1) + 1.5 * (sin(x0*x1)) + epsilon
    sigma_sq = 0.1
    """
    sigma = 0.1 ** 0.50
    
    x1 = np.random.uniform(0.1, 3.0, n_train)
    x2 = np.random.uniform(4.1, 6.0, n_train)
    x1 = pd.DataFrame(x1)
    x2 = pd.DataFrame(x2)
    Xtrain = pd.concat([x1, x2], axis=1)
    ytrain = 1.35 * (Xtrain.iloc[:,0]*Xtrain.iloc[:,1]) + 1.50 * (np.sin((Xtrain.iloc[:,0])*(Xtrain.iloc[:,1]))) + np.random.normal(0, sigma, n_train)

    x1_test = np.random.uniform(0.1, 3.0, n_test)
    x2_test = np.random.uniform(4.1, 6.0, n_test)
    x1_test = pd.DataFrame(x1_test)
    x2_test = pd.DataFrame(x2_test)
    Xtest = pd.concat([x1_test, x2_test], axis=1)
    ytest = 1.35 * (Xtest.iloc[:, 0] * Xtest.iloc[:, 1]) + 1.50 * (np.sin((Xtest.iloc[:, 0]) * (Xtest.iloc[:, 1]))) +np.random.normal(0, sigma, n_test)
    return Xtrain, ytrain, Xtest, ytest

In [56]:
def f2(n_train=100,n_test=30):
    """
    y = 1.5 * exp(x0) + 5.0 * cos(x1) + epsilon
    sigma_sq = 0.1
    """
    sigma = 0.1 ** 0.50
    
    x1 = np.random.uniform(0.1, 0.5, n_train)
    x2 = np.random.uniform(1.0, 1.5, n_train)
    x1 = pd.DataFrame(x1)
    x2 = pd.DataFrame(x2)
    Xtrain = pd.concat([x1, x2], axis=1)
    ytrain = (1.5 * np.exp(Xtrain.iloc[:, 0])) + (5.0 * np.cos(Xtrain.iloc[:, 1])) + np.random.normal(0, sigma, n_train)

    x1_test = np.random.uniform(0.1, 3.0, n_test)
    x2_test = np.random.uniform(4.1, 6.0, n_test)
    x1_test = pd.DataFrame(x1_test)
    x2_test = pd.DataFrame(x2_test)
    Xtest = pd.concat([x1_test, x2_test], axis=1)
    ytest = (1.5 * np.exp(Xtest.iloc[:, 0])) + (5.0 * np.cos(Xtest.iloc[:, 1])) + np.random.normal(0, sigma, n_test)
    return Xtrain, ytrain, Xtest, ytest

In [5]:
def f3(n_train=100,n_test=30):
    """
    y = 6 * (sin(x0)*cos(x1)) + epsilon
    sigma_sq = 0.1
    """
    sigma = 0.1 ** 0.50
    
    x1 = np.random.uniform(-1, 1, n_train)
    x2 = np.random.uniform(1.5, 2, n_train)
    x1 = pd.DataFrame(x1)
    x2 = pd.DataFrame(x2)
    Xtrain = pd.concat([x1, x2], axis=1)
    ytrain = 6.0 * np.sin(Xtrain.iloc[:, 0]) * np.cos(Xtrain.iloc[:, 1]) + np.random.normal(0, sigma, n_train)

    x1_test = np.random.uniform(-1, 1, n_test)
    x2_test = np.random.uniform(1.5, 2, n_test)
    x1_test = pd.DataFrame(x1_test)
    x2_test = pd.DataFrame(x2_test)
    Xtest = pd.concat([x1_test, x2_test], axis=1)
    ytest = 6.0 * np.sin(Xtest.iloc[:, 0]) * np.cos(Xtest.iloc[:, 1]) + np.random.normal(0, sigma, n_test)
    return Xtrain, ytrain, Xtest, ytest

In [3]:
# Testing BSR using f1

K = 2 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 2, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [4]:
random.seed(10)

n_train = 100
n_test = 30
Xtrain, ytrain, Xtest, ytest = f1(n_train, n_test)

numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = ytest.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(Xtrain, ytrain)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(Xtest)
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y1) ** 0.50)

runtime = time.time() - st

/Users/somjit/anaconda3/lib/python3.11/site-packages/bsr-0.1.1-py3.11.egg/bsr/funcs.py:205: RuntimeWarning: overflow encountered in power
/Users/somjit/anaconda3/lib/python3.11/site-packages/bsr-0.1.1-py3.11.egg/bsr/funcs.py:203: RuntimeWarning: overflow encountered in square
/Users/somjit/anaconda3/lib/python3.11/site-packages/bsr-0.1.1-py3.11.egg/bsr/funcs.py:199: RuntimeWarning: invalid value encountered in sin


LinAlgError: SVD did not converge

In [25]:
model_expression

[['(x[0])*((sin(x[0]))^2)', 'sin((x[1])^3)'],
 ['-(x[1]+sin(x[1]))', '(x[1]+x[0])^2'],
 ['(1/[exp((x[0])*(x[1]))])*((x[1])*(x[0]))', '-((x[0])*(x[1]))'],
 ['-(-(-(-(-((x[0]+x[0]+x[0])*(x[1]+x[1]))))))+((cos(sin(x[1])))^3)^2',
  'sin(-(sin(sin(-((-(-(-(x[0]))))*(-(x[1])))))))'],
 ['1/[(x[0])^2]+(x[1])^3+x[0]', '-(x[0])'],
 ['(1/[sin(x[1])])^2', 'x[1]+exp(x[0])'],
 ['(x[1])*(x[0])+sin(((x[0])^3)*(x[0]))', '(x[1])^2'],
 ['-(x[0]+x[0])', 'sin(sin(cos(x[1])))'],
 ['((x[0])*(sin(x[0]+-(x[0])))+x[0])^3', 'exp(x[0])'],
 ['cos((x[1])^2)', '(x[1]+(x[1]+x[0])^3)^2']]

In [26]:
rmse

[36.551823215286944,
 45.956191812950195,
 46.06150410510851,
 46.24858765643355,
 44.66995317783747,
 44.42601102338313,
 46.1103491552694,
 45.58449278569239,
 47.62220014852188,
 48.71576025438018]

In [27]:
runtime

198.46101307868958

In [28]:
beta_hat

[array([[ 7.92469364],
        [ 3.70750232],
        [-0.54414212]]),
 array([[2.52452053],
        [3.24764354],
        [0.49552921]]),
 array([[-0.72652315],
        [ 5.68167047],
        [-1.42922337]]),
 array([[ 0.08684445],
        [-0.22542654],
        [ 1.93773102]]),
 array([[-3.26535897],
        [ 0.02859256],
        [-6.59379679]]),
 array([[-1.7004743 ],
        [ 0.30142384],
        [ 1.03292324]]),
 array([[ 6.37935187e-01],
        [ 1.28880243e+00],
        [-6.06420339e-04]]),
 array([[ 0.29524727],
        [-3.20584219],
        [ 2.79062957]]),
 array([[-5.36834948],
        [-3.46472445],
        [ 6.17903652]]),
 array([[ 1.09072798e-03],
        [-2.88553372e-05],
        [ 8.04034684e-05]])]

In [57]:
# Testing BSR using f2

K = 2 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 2, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [58]:
random.seed(10)

n_train = 100
n_test = 30
Xtrain, ytrain, Xtest, ytest = f2(n_train, n_test)

numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = ytest.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(Xtrain, ytrain)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(Xtest)
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y1) ** 0.50)

runtime = time.time() - st

LinAlgError: SVD did not converge

In [52]:
model_expression

[['(x[0])*(x[1])', '-((x[0])^2)']]

In [ ]:
rmse

In [ ]:
runtime

In [ ]:
beta_hat

In [80]:
# Testing BSR using f3
from codes.bsr_class_f3 import BSR
K = 2 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 2, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [81]:
n_train = 100
n_test = 30
Xtrain, ytrain, Xtest, ytest = f3(n_train, n_test)

y1 = ytest.to_numpy()
st = time.time()


my_bsr.fit(Xtrain, ytrain)
model_expression = my_bsr.model()
fitted_y, beta_hat[i] = my_bsr.predict(Xtest)
rmse = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y1) ** 0.50)

runtime = time.time() - st

In [82]:
model_expression

['(((sin(x[0]))*(sin(cos(cos(x[1])))))*((sin(x[1]))*(sin(x[1]))))*(sin((sin(sin(((sin((cos(x[1]))*(sin((sin(x[1]))*(x[1])))))*(sin(x[1])))*(x[1]))))*(x[1])))',
 'cos(sin((((sin(((cos(sin(sin(sin(((cos(x[0]))*(cos(sin(x[0]))))*(x[0]))))))*(x[1]))*(((cos(x[1]))*(x[1]))*(x[1]))))*(sin(x[1])))*(x[0]))*(x[0])))']

In [83]:
rmse

4.90364346878033

In [84]:
runtime

230.51564693450928

In [85]:
beta_hat

[array([[-1.00818291],
        [ 2.91431789],
        [ 1.0418825 ]])]