In [48]:
from codes.bsr_class_Single_Atom import symreg
from codes.bsr_class_Single_Atom import BSR
import pandas as pd
import numpy as np
import random
import time
from sklearn.model_selection import train_test_split

In [49]:
y = pd.read_csv("y_catalysis")
X = pd.read_csv("X_catalysis")
X = X.drop(X.columns[0], axis = 1)
y = y.drop(y.columns[0], axis = 1)
y = y.squeeze(axis=0)
y = y.iloc[:,0]

In [50]:
X_stage1 = X.loc[:, ['Hfo', 'Oxv']]
y_stage1 = y

In [18]:
K = 2 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 2, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [19]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y_stage1.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X_stage1, y_stage1)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X_stage1)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

0
1
2
3
4
5
6
7
8
9


In [20]:
min(rmse), rmse.index(min(rmse)), model_expression[rmse.index(min(rmse))], beta_hat[rmse.index(min(rmse))]

(1.4784522183884894,
 6,
 ['-(x[0])', '(x[0])*(x[1])+x[1]'],
 array([[1.95726691e-15],
        [1.22202252e+00],
        [1.54443009e+00]]))

In [12]:
K = 3 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 3, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)

In [13]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y_stage1.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X_stage1, y_stage1)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X_stage1)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

0
1
2
3
4
5
6
7
8
9


In [16]:
min(rmse), rmse.index(min(rmse)), model_expression[rmse.index(min(rmse))], beta_hat[rmse.index(min(rmse))]

(1.34481298122193,
 2,
 ['(x[1])^2', '-(x[1]+x[1])', '-(x[0]+x[0])'],
 array([[ 0.612088  ],
        [-0.61888908],
        [-0.93212947],
        [ 0.61101144]]))

In [21]:
K = 4 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 4, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)


In [22]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y_stage1.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X_stage1, y_stage1)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X_stage1)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

0
1
2
3
4
5
6
7
8
9


In [23]:
min(rmse), rmse.index(min(rmse)), model_expression[rmse.index(min(rmse))], beta_hat[rmse.index(min(rmse))]

(1.1961224190500388,
 2,
 ['(-(x[0]))*(x[1]+x[1])',
  '(1/[x[0]])*(-(x[1]))',
  '((x[1])^2)*(x[0])',
  '((x[1])*(x[1]))*(x[1])'],
 array([[ 0.33121259],
        [-0.33904085],
        [ 0.0153245 ],
        [-0.65789134],
        [ 0.76981609]]))

In [51]:
K = 5 # number of trees
MM = 100 # number of iterations
hyper_params = [{'treeNum': 5, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(K,MM)


In [52]:
numiter = 10
rmse = [0] * (numiter)
model_expression = [0] * (numiter)
beta_hat = [0] * (numiter)
y1 = y_stage1.to_numpy()
st = time.time()

for i in range(numiter):
    my_bsr.fit(X_stage1, y_stage1)
    model_expression[i] = my_bsr.model()
    fitted_y, beta_hat[i] = my_bsr.predict(X_stage1)
    fitted_y = fitted_y.flatten()
    rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y) ** 0.50)
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
min(rmse), rmse.index(min(rmse)), model_expression[rmse.index(min(rmse))], beta_hat[rmse.index(min(rmse))]

(0.9019991533353605,
 2,
 ['(x[1])*(x[0])',
  '((x[0])*(x[1]))*(-(-(x[1])))',
  '1/[x[0]+(x[1])^2]',
  '(x[1])^2+x[0]+x[0]',
  '-(x[1])'],
 array([[ 0.52830202],
        [ 0.84885599],
        [-0.23174193],
        [-0.00586581],
        [-0.52904645],
        [-1.89986947]]))

In [33]:
from codes.bsr_class_Single_Atom import symreg
from codes.bsr_class_Single_Atom import BSR
import pandas as pd
import numpy as np
import random
import time
from sklearn.model_selection import train_test_split

In [34]:
y = pd.read_csv("y_catalysis")
X = pd.read_csv("X_catalysis")
X = X.drop(X.columns[0], axis = 1)
y = y.drop(y.columns[0], axis = 1)
y = y.squeeze(axis=0)
y = y.iloc[:,0]

X_stage1 = X.loc[:, ['Hfo', 'Oxv']]
y_stage1 = y

In [15]:
# Set the test size ratio
test_ratio = 0.2

# Sample training set
X_train = X_stage1.sample(frac=1 - test_ratio, random_state=42)
y_train = y.loc[X_train.index]

# Get the remaining data for testing
X_test = X_stage1.drop(X_train.index)
y_test = y.drop(X_train.index)

In [20]:
X_train, X_stage1

(         Hfo       Oxv
 40 -1.260158  0.024281
 22  1.707421  1.387072
 55 -0.763606 -1.911537
 88  1.871504  1.101206
 0  -1.454906 -0.186248
 ..       ...       ...
 48  1.707421  0.024281
 80 -0.030109  1.101206
 57 -0.189148 -1.911537
 32 -0.906405 -0.132612
 86 -0.257303  1.101206
 
 [73 rows x 2 columns],
          Hfo       Oxv
 0  -1.454906 -0.186248
 1  -1.260158 -0.186248
 2  -0.030109 -0.186248
 3  -0.763606 -0.186248
 4   0.713106 -0.186248
 ..       ...       ...
 86 -0.257303  1.101206
 87  1.707421  1.101206
 88  1.871504  1.101206
 89  0.722252  1.101206
 90  0.227986  1.101206
 
 [91 rows x 2 columns])

In [32]:
#X_train, X_test, y_train, y_test = train_test_split(X_stage1, y_stage1, test_size=0.1, random_state=d+1)
k=2
MM = 100 # number of iterations
hyper_params = [{'treeNum': k, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
my_bsr = BSR(k,MM)
X = X_stage1.sample(frac=0.9, random_state=42)
X.reset_index(drop=True)
y1 = y_stage1.loc[X_train.index]
y1 = y1.reset_index(drop=True)
my_bsr.fit(X, y1)

In [ ]:
data_rep = 25
K = [2, 3, 4, 5]
rmse_BSR = np.zeros((data_rep, len(K)))

for d in range(data_rep):
    
    X_train, X_test, y_train, y_test = train_test_split(X_stage1, y_stage1, test_size=0.1, random_state=d+1)
    X_train = X_train.reset_index(drop=True)
    X_test = X_test.reset_index(drop=True)
    y_train = y_train.reset_index(drop=True)
    y_test = y_test.reset_index(drop=True)
    
    for k in K:
        MM = 100 # number of iterations
        hyper_params = [{'treeNum': k, 'itrNum':100, 'alpha1':0.4, 'alpha2':0.4, 'beta':-1.2}]
        my_bsr = BSR(k,MM)
        numiter = 10
        rmse = [0] * (numiter)
        #model_expression = [0] * (numiter)
        beta_hat = [0] * (numiter)
        y1 = y_test.to_numpy()
    
        for i in range(numiter):
            my_bsr.fit(X_train, y_train)
            #model_expression[i] = my_bsr.model()
            fitted_y, beta_hat[i] = my_bsr.predict(X_test)
            fitted_y = fitted_y.flatten()
            rmse[i] = (np.sum((y1 - fitted_y) ** 2) ** 0.50)/(len(y1) ** 0.50)
            print("Iteration:", i)
    
        rmse_BSR[d][k-2] = min(rmse)
        print("Tree:", k)
    print("Data replication:", d+1)

Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 2
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 3
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 4
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 5
Data replication: 1
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 2
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 3
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 4
Iteration: 0
I

Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 3
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 4
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 5
Data replication: 15
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 2
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 3
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 4
Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
Iteration: 7
Iteration: 8
Iteration: 9
Tree: 5
Data replication: 16
Iteration: 0
Iteration: 1
Iteration: 2
Itera